appName: "Loader Server"

scheduledExecutorConfig:
  threadPoolSize: 10
  counterCompoundThreadInterval: 10000
  counterThroughputThreadInterval: 10000
  groupConfConsolidationThreadInterval: 10000
  jobDispatcherThreadInterval: 1000
  timerComputationThreadInterval: 10000

resourceStorageFSConfig:
  udfLibsPath: "/usr/share/loader-server/libs"
  udfUnDeployedLibsPath: "/usr/share/loader-server/unDeployedLibs"
  userClassInfoPath: "/usr/share/loader-server/config"
  userClassLibMappingFile: "/usr/share/loader-server/config/classLibMapping.properties"
  platformLibPath: "/usr/share/loader-server/platformLibs"
  inputFilesPath: "/usr/share/loader-server/inputFiles"
  inputFileFolderPath: "/usr/share/loader-server/inputFiles/{resourceName}"
  inputFilePath: "/usr/share/loader-server/inputFiles/{resourceName}/inputFile"
  inputFileAgentDeploymentPath: "/usr/share/loader-server/inputFiles/{resourceName}/agentDeployment.txt"

agentConfig:
  agentPort: 8888
  agentsPath: "/usr/share/loader-server/agents"
  agentInfoFile: "/usr/share/loader-server/agents/{agentIp}/agentInfo.json"
  agentPlatformLibInfoFile: "/usr/share/loader-server/agents/{agentIp}/deployment/platform.properties"
  agentClassLibInfoFile: "/usr/share/loader-server/agents/{agentIp}/deployment/classLib.properties"
  jobLogUrl: "http://{agentIp}:{port}/loader-agent/jobs/{jobId}/log"

monitoringAgentConfig:
  agentPort: 7777

jobFSConfig:
  businessUnitsPath: "/var/log/loader-server/businessUnits"
  businessUnitFile: "/var/log/loader-server/businessUnits/{businessUnit}"
  runsPath: "/var/log/loader-server/runs"
  runPath: "/var/log/loader-server/runs/{runName}"
  runVersionsPath: "/var/log/loader-server/runs/{runName}/versions"
  runMetaInfoFile: "/var/log/loader-server/runs/{runName}/meta.properties"
  runFile: "/var/log/loader-server/runs/{runName}/versions/{version}/run.json"
  runJobsFile: "/var/log/loader-server/runs/{runName}/versions/{version}/jobs.txt"
  runAllJobsFile: "/var/log/loader-server/runs/{runName}/jobs.txt"
  jobsPath: "/var/log/loader-server/jobs"
  jobRunFile: "/var/log/loader-server/jobs/{jobId}/run.json"
  jobPath: "/var/log/loader-server/jobs/{jobId}"
  jobStatusFile: "/var/log/loader-server/jobs/{jobId}/status.json"
  jobStatsPath: "/var/log/loader-server/jobs/{jobId}/jobStats"
  jobGroupStatsPath: "/var/log/loader-server/jobs/{jobId}/jobStats/{groupName}"
  jobFunctionStatsPath: "/var/log/loader-server/jobs/{jobId}/jobStats/{groupName}/functions/{functionName}"
  jobFunctionTimersStatsPath: "/var/log/loader-server/jobs/{jobId}/jobStats/{groupName}/functions/{functionName}/timers"
  jobFunctionCountersStatsPath: "/var/log/loader-server/jobs/{jobId}/jobStats/{groupName}/functions/{functionName}/counters"
  jobFunctionHistogramStatsPath: "/var/log/loader-server/jobs/{jobId}/jobStats/{groupName}/functions/{functionName}/histograms"
  jobMetricStatsFile: "/var/log/loader-server/jobs/{jobId}/jobStats/{groupName}/functions/{functionName}/{metricType}/{metricName}/agents/{agentIp}/data.stats"
  jobMonitoringStatsPath: "/var/log/loader-server/jobs/{jobId}/monitoringStats"
  jobResourceMonitoringFile: "/var/log/loader-server/jobs/{jobId}/monitoringStats/agents/{agentIp}/Resources/{resource}.txt"
  jobHealthStatusFile: "/var/log/loader-server/jobs/{jobId}/monitoringStats/agents/{agentIp}/Resources/agentHealth.txt"
  runningJobsFile: "/var/log/loader-server/jobs/runningJobs"
  queuedJobsFile: "/var/log/loader-server/jobs/queuedJobs"
  jobGroupConfFile: "/var/log/loader-server/jobs/{jobId}/jobStats/{groupName}/conf/realTimeConf/agents/{agentIp}/data.stats"
  workflowJobsPath: "/var/log/loader-server/workflowJobs"
  workflowJobPath:  "/var/log/loader-server/workflowJobs/{workflowId}"
  workflowJobStatusPath: "/var/log/loader-server/workflowJobs/{workflowId}/status.json"
  scheduledWorkflowsPath: "/var/log/loader-server/workflows"
  scheduledWorkflowPath: "/var/log/loader-server/workflows/{workflowName}"
  scheduledWorkflowRunningFile: "/var/log/loader-server/workflows/{workflowName}/runningWorkflowJobs"
  scheduledWorkflowJobsFile: "/var/log/loader-server/workflows/{workflowName}/workflowJobs"

jMetricConfig:
  archivalEngineClass: "nitinka.jmetrics.archive.RRD4JArchivingEngine"
  configParams:
    basePath: "/var/log/loader-server/systemStats"

reportConfigFile: /etc/loader-server/reportConfig.json

dataFixConfig:
  dataFixersFile: /etc/loader-server/dataFixers.json
  doneFixersFile: /var/log/loader-server/jobs/doneFixers.json

http:
  port: 9999
  adminPort: 9991
  rootPath: "/loader-server/*"

logging:
  level: INFO
